# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 1
updates:
  #Web
  - package-ecosystem: "nuget"
    directory: "/src/Web/PanacheSoftware.UI.Core"
    schedule: "weekly"
  #Web Apps
  - package-ecosystem: "nuget"
    directory: "/src/Web Apps/PanacheSoftware.Identity"
    schedule: "weekly"
  - package-ecosystem: "nuget"
    directory: "/src/Web Apps/PanacheSoftware.UI.Client"
    schedule: "weekly"
  #Services
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.Client"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.File"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.Folder"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.Foundation"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.Task"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Services/PanacheSoftware.Service.Team"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  #Core
  - package-ecosystem: "nuget"
    directory: "/src/Core/PanacheSoftware.Core"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Core/PanacheSoftware.Database"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  - package-ecosystem: "nuget"
    directory: "/src/Core/PanacheSoftware.Http"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"
  #API Gateway
  - package-ecosystem: "nuget"
    directory: "/src/API Gateway/PanacheSoftware.API.Gateway"
    schedule: "weekly"
    reviewers:
      - "PanacheSoftwareDev"

