version: "3.4"
services:

  panachesoftware.identity:
    image: panachesoftware/panachesoftwareidentity-arm32:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.Identity;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__UIClientURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55001
      - PanacheSoftware__Url__UIClientURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44301
      - PanacheSoftware__Secret__UIClientSecret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
      - PanacheSoftware__Secret__APIGatewaySecret=DDDCB193-213C-43FB-967A-5A911D2EFC04
      - PanacheSoftware__Secret__ClientServiceSecret=1314EF18-40FA-4B16-83DF-B276FF0D92A9
      - PanacheSoftware__Secret__FileServiceSecret=839C649E-4FE3-410C-B43F-69C017A52676
      - PanacheSoftware__Secret__FoundationServiceSecret=70CD8BB9-5256-42CF-8B95-DD61C1051AD0
      - PanacheSoftware__Secret__TaskServiceSecret=AC654B02-E46B-4359-B908-87479CBE1CEB
      - PanacheSoftware__Secret__TeamServiceSecret=5C9BF545-3C20-4448-9EEC-6B3E745B671E
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55002:80"
    restart: always

  panachesoftware.service.team:
    image: panachesoftware/panachesoftwareserviceteam-arm32:latest
    depends_on:
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.Team;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Secret__TeamServiceSecret=5C9BF545-3C20-4448-9EEC-6B3E745B671E
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55006:80"
    restart: always

  panachesoftware.service.task:
    image: panachesoftware/panachesoftwareservicetask-arm32:latest
    depends_on:
      - panachesoftware.identity
      - panachesoftware.service.team
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.Task;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Url__TeamServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55006
      - PanacheSoftware__Url__TeamServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44306
      - PanacheSoftware__Secret__TaskServiceSecret=AC654B02-E46B-4359-B908-87479CBE1CEB
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55007:80"
    restart: always

  panachesoftware.service.foundation:
    image: panachesoftware/panachesoftwareservicefoundation-arm32:latest
    depends_on:
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.Foundation;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Secret__FoundationServiceSecret=70CD8BB9-5256-42CF-8B95-DD61C1051AD0
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55004:80"
    restart: always

  panachesoftware.service.file:
    image: panachesoftware/panachesoftwareservicefile-arm32:latest
    depends_on:
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.File;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Secret__FileServiceSecret=839C649E-4FE3-410C-B43F-69C017A52676
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55008:80"
    restart: always

  panachesoftware.service.client:
    image: panachesoftware/panachesoftwareserviceclient-arm32:latest
    depends_on:
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server={ip address of MySQL server};port=3306;database=PanacheSoftware.Client;user=pi;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Secret__ClientServiceSecret=1314EF18-40FA-4B16-83DF-B276FF0D92A9
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55005:80"
    restart: always

  panachesoftware.ui.client:
    image: panachesoftware/panachesoftwareuiclient-arm32:latest
    depends_on:
      - panachesoftware.identity
      - panachesoftware.service.team
      - panachesoftware.service.task
      - panachesoftware.service.foundation
      - panachesoftware.service.file
      - panachesoftware.service.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44302
      - PanacheSoftware__Url__APIGatewayURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55003
      - PanacheSoftware__Url__APIGatewayURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44303
      - PanacheSoftware__Url__UIClientURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55001
      - PanacheSoftware__Url__UIClientURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44301
      - PanacheSoftware__Url__ClientServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55005
      - PanacheSoftware__Url__ClientServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44305
      - PanacheSoftware__Url__FileServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55008
      - PanacheSoftware__Url__FileServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44308
      - PanacheSoftware__Url__FoundationServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55004
      - PanacheSoftware__Url__FoundationServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44304
      - PanacheSoftware__Url__TaskServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55007
      - PanacheSoftware__Url__TaskServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44307
      - PanacheSoftware__Url__TeamServiceURL=http://{ip address of host or 172.17.0.1 if only accessing locally}:55006
      - PanacheSoftware__Url__TeamServiceURLSecure=https://{ip address of host or 172.17.0.1 if only accessing locally}:44306
      - PanacheSoftware__Secret__UIClientSecret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
    ports:
      - "{delete this if running locally, otherwise ip address of host i.e. 123.456.78.900:}55001:80"
    restart: always
