version: "3.4"
services:
    
  sqldata:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd123!
    volumes:
      - panachesoftware-sqldata:/var/opt/mssql
    
  panachesoftware.identity:
    image: panachesoftware/panachesoftwareidentity:latest
    depends_on:
      - sqldata
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.Identity;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__UIClientURL=http://host.docker.internal:55001
      - PanacheSoftware__Url__UIClientURLSecure=https://host.docker.internal:44301
      - PanacheSoftware__Secret__UIClientSecret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
      - PanacheSoftware__Secret__APIGatewaySecret=DDDCB193-213C-43FB-967A-5A911D2EFC04
      - PanacheSoftware__Secret__ClientServiceSecret=1314EF18-40FA-4B16-83DF-B276FF0D92A9
      - PanacheSoftware__Secret__FileServiceSecret=839C649E-4FE3-410C-B43F-69C017A52676
      - PanacheSoftware__Secret__FoundationServiceSecret=70CD8BB9-5256-42CF-8B95-DD61C1051AD0
      - PanacheSoftware__Secret__TaskServiceSecret=AC654B02-E46B-4359-B908-87479CBE1CEB
      - PanacheSoftware__Secret__TeamServiceSecret=5C9BF545-3C20-4448-9EEC-6B3E745B671E
    ports:
      - "55002:80"
    restart: always

  panachesoftware.service.team:
    image: panachesoftware/panachesoftwareserviceteam:latest
    depends_on:
      - sqldata
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.Team;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Secret__TeamServiceSecret=5C9BF545-3C20-4448-9EEC-6B3E745B671E
    ports:
      - "55006:80"
    restart: always

  panachesoftware.service.task:
    image: panachesoftware/panachesoftwareservicetask:latest
    depends_on:
      - sqldata
      - panachesoftware.identity
      - panachesoftware.service.team
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.Task;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Url__TeamServiceURL=http://host.docker.internal:55006
      - PanacheSoftware__Url__TeamServiceURLSecure=https://host.docker.internal:44306
      - PanacheSoftware__Secret__TaskServiceSecret=AC654B02-E46B-4359-B908-87479CBE1CEB
    ports:
      - "55007:80"
    restart: always

  panachesoftware.service.foundation:
    image: panachesoftware/panachesoftwareservicefoundation:latest
    depends_on:
      - sqldata
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.Foundation;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Secret__FoundationServiceSecret=70CD8BB9-5256-42CF-8B95-DD61C1051AD0
    ports:
      - "55004:80"
    restart: always

  panachesoftware.service.file:
    image: panachesoftware/panachesoftwareservicefile:latest
    depends_on:
      - sqldata
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.File;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Secret__FileServiceSecret=839C649E-4FE3-410C-B43F-69C017A52676
    ports:
      - "55008:80"
    restart: always

  panachesoftware.service.client:
    image: panachesoftware/panachesoftwareserviceclient:latest
    depends_on:
      - sqldata
      - panachesoftware.identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySQL=server=sqldata;port=3306;database=PanacheSoftware.Client;user=root;password=Passw0rd123!;GuidFormat=Char36
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__DBProvider=MySQL
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Secret__ClientServiceSecret=1314EF18-40FA-4B16-83DF-B276FF0D92A9
    ports:
      - "55005:80"
    restart: always

  panachesoftware.ui.client:
    image: panachesoftware/panachesoftwareuiclient:latest
    depends_on:
      - panachesoftware.identity
      - panachesoftware.service.team
      - panachesoftware.service.task
      - panachesoftware.service.foundation
      - panachesoftware.service.file
      - panachesoftware.service.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - PanacheSoftware__CallMethod__APICallsSecure=False
      - PanacheSoftware__CallMethod__UICallsSecure=False
      - PanacheSoftware__CallMethod__UseAPIGateway=False
      - PanacheSoftware__StartDomain=panachesoftware.com
      - PanacheSoftware__Url__IdentityServerURL=http://host.docker.internal:55002
      - PanacheSoftware__Url__IdentityServerURLSecure=https://host.docker.internal:44302
      - PanacheSoftware__Url__APIGatewayURL=http://host.docker.internal:55003
      - PanacheSoftware__Url__APIGatewayURLSecure=https://host.docker.internal:44303
      - PanacheSoftware__Url__UIClientURL=http://host.docker.internal:55001
      - PanacheSoftware__Url__UIClientURLSecure=https://host.docker.internal:44301
      - PanacheSoftware__Url__ClientServiceURL=http://host.docker.internal:55005
      - PanacheSoftware__Url__ClientServiceURLSecure=https://host.docker.internal:44305
      - PanacheSoftware__Url__FileServiceURL=http://host.docker.internal:55008
      - PanacheSoftware__Url__FileServiceURLSecure=https://host.docker.internal:44308
      - PanacheSoftware__Url__FoundationServiceURL=http://host.docker.internal:55004
      - PanacheSoftware__Url__FoundationServiceURLSecure=https://host.docker.internal:44304
      - PanacheSoftware__Url__TaskServiceURL=http://host.docker.internal:55007
      - PanacheSoftware__Url__TaskServiceURLSecure=https://host.docker.internal:44307
      - PanacheSoftware__Url__TeamServiceURL=http://host.docker.internal:55006
      - PanacheSoftware__Url__TeamServiceURLSecure=https://host.docker.internal:44306
      - PanacheSoftware__Secret__UIClientSecret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
    ports:
      - "55001:80"
    restart: always

volumes:
  panachesoftware-sqldata:
    external: false