// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanacheSoftware.Service.Team.Persistance.Context;

namespace PanacheSoftware.Service.Team.Persistance.Data.Migrations
{
    [DbContext(typeof(PanacheSoftwareServiceTeamContext))]
    partial class PanacheSoftwareServiceTeamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Join.UserTeam", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("CreatedBy");

                b.Property<DateTime>("CreatedDate");

                b.Property<DateTime>("DateFrom");

                b.Property<DateTime>("DateTo");

                b.Property<Guid>("LastUpdateBy");

                b.Property<DateTime>("LastUpdateDate");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("varchar(25)");

                b.Property<Guid>("TeamHeaderId");

                b.Property<Guid>("TenantId");

                b.Property<Guid>("UserId");

                b.HasKey("Id");

                b.HasIndex("TeamHeaderId");

                b.ToTable("UserTeam");
            });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Team.TeamDetail", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("CreatedBy");

                b.Property<DateTime>("CreatedDate");

                b.Property<DateTime>("DateFrom");

                b.Property<DateTime>("DateTo");

                b.Property<Guid>("LastUpdateBy");

                b.Property<DateTime>("LastUpdateDate");

                b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<Guid>("TeamHeaderId");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TeamHeaderId")
                        .IsUnique();

                    b.ToTable("TeamDetail");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Team.TeamHeader", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<Guid>("CreatedBy");

                b.Property<DateTime>("CreatedDate");

                b.Property<DateTime>("DateFrom");

                b.Property<DateTime>("DateTo");

                b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ParentTeamId");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ParentTeamId");

                    b.ToTable("TeamHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Join.UserTeam", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.Team.TeamHeader", "TeamHeader")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Team.TeamDetail", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.Team.TeamHeader", "TeamHeader")
                        .WithOne("TeamDetail")
                        .HasForeignKey("PanacheSoftware.Core.Domain.Team.TeamDetail", "TeamHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.Team.TeamHeader", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.Team.TeamHeader", "ParentTeam")
                        .WithMany("ChildTeams")
                        .HasForeignKey("ParentTeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
