// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanacheSoftware.Service.CustomField.Persistance.Context;

namespace PanacheSoftware.Service.CustomField.Persistance.Data.Migrations
{
    [DbContext(typeof(PanacheSoftwareServiceCustomFieldContext))]
    [Migration("20210315152848_AddCustomFieldGroupLinks")]
    partial class AddCustomFieldGroupLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomFieldGroupHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldGroupTag")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FieldGroupType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldGroupHeaderId")
                        .IsUnique();

                    b.ToTable("CustomFieldGroupDetail");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomFieldGroupHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldGroupHeaderId");

                    b.ToTable("CustomFieldGroupLink");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomFieldGroupHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomFieldType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("GDPR")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("History")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldGroupHeaderId");

                    b.ToTable("CustomFieldHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldTag");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomFieldHeaderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldHeaderId");

                    b.ToTable("CustomFieldValue");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValueHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CustomFieldValueId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("LastUpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OriginalCreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldValueId");

                    b.ToTable("CustomFieldValueHistory");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupDetail", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", "CustomFieldGroupHeader")
                        .WithOne("CustomFieldGroupDetail")
                        .HasForeignKey("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupDetail", "CustomFieldGroupHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupLink", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", "CustomFieldGroupHeader")
                        .WithMany()
                        .HasForeignKey("CustomFieldGroupHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", "CustomFieldGroupHeader")
                        .WithMany("CustomFieldHeaders")
                        .HasForeignKey("CustomFieldGroupHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", "CustomFieldHeader")
                        .WithMany()
                        .HasForeignKey("CustomFieldHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValueHistory", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", "CustomFieldValue")
                        .WithMany("CustomFieldValueHistorys")
                        .HasForeignKey("CustomFieldValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldValue");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", b =>
                {
                    b.Navigation("CustomFieldGroupDetail");

                    b.Navigation("CustomFieldHeaders");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.Navigation("CustomFieldValueHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
