// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PanacheSoftware.Service.CustomField.Persistance.Context;

namespace PanacheSoftware.Service.CustomField.Persistance.Data.Migrations
{
    [DbContext(typeof(PanacheSoftwareServiceCustomFieldContext))]
    [Migration("20210302120505_Standard")]
    partial class Standard
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("CustomFieldHeaderId");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldHeaderId")
                        .IsUnique();

                    b.ToTable("CustomFieldDetail");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("CustomFieldGroupHeaderId");

                    b.Property<Guid>("CustomFieldHeaderId");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldGroupHeaderId");

                    b.ToTable("CustomFieldGroupDetail");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CustomFieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("GDPR")
                        .HasColumnType("bit");

                    b.Property<bool>("History")
                        .HasColumnType("bit");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("CustomFieldTag");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("CustomFieldHeaderId");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<Guid>("LinkId");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldHeaderId");

                    b.ToTable("CustomFieldValue");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValueHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("CustomFieldValueId");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("LastUpdateBy");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<Guid>("LinkId");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OriginalCreationDate");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("CustomFieldValueId");

                    b.ToTable("CustomFieldValueHistory");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldDetail", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", "CustomFieldHeader")
                        .WithOne("CustomFieldDetail")
                        .HasForeignKey("PanacheSoftware.Core.Domain.CustomField.CustomFieldDetail", "CustomFieldHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupDetail", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", "CustomFieldGroupHeader")
                        .WithMany("CustomFieldGroupDetails")
                        .HasForeignKey("CustomFieldGroupHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldGroupHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", "CustomFieldHeader")
                        .WithMany()
                        .HasForeignKey("CustomFieldHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldHeader");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValueHistory", b =>
                {
                    b.HasOne("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", "CustomFieldValue")
                        .WithMany("CustomFieldValueHistorys")
                        .HasForeignKey("CustomFieldValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomFieldValue");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldGroupHeader", b =>
                {
                    b.Navigation("CustomFieldGroupDetails");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldHeader", b =>
                {
                    b.Navigation("CustomFieldDetail");
                });

            modelBuilder.Entity("PanacheSoftware.Core.Domain.CustomField.CustomFieldValue", b =>
                {
                    b.Navigation("CustomFieldValueHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
