apiVersion: apps/v1
kind: Deployment
metadata:
  name: panachesoftware-identity
  labels:
    app: panachesoftware-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panachesoftware-identity
  template:
    metadata:
      labels:
        app: panachesoftware-identity
    spec:
      containers:
      - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:55002
          - name: ConnectionStrings__MySQL
            value: server={db-server-IP};port=3306;database=PanacheSoftware.Identity.K8S;user={db-user};password={db-password};GuidFormat=Char36
          - name: PanacheSoftware__CallMethod__APICallsSecure
            value: "False"
          - name: PanacheSoftware__CallMethod__UICallsSecure
            value: "False"
          - name: PanacheSoftware__CallMethod__UseAPIGateway
            value: "True"
          - name: PanacheSoftware__DBProvider
            value: MySQL
          - name: PanacheSoftware__Secret__AutomationServiceSecret
            value: C4CCF7EA-0F2D-4BF8-8941-98D43A5E1605
          - name: PanacheSoftware__Secret__APIGatewaySecret
            value: D32CAA87-2F1F-4D35-B2DF-C712C2AFF6C3
          - name: PanacheSoftware__Secret__ClientServiceSecret
            value: AA04416A-A87B-4D88-956B-27CBFFCC2802
          - name: PanacheSoftware__Secret__FileServiceSecret
            value: 6D20E27B-18EE-4694-AFB7-929343F51D43
          - name: PanacheSoftware__Secret__FoundationServiceSecret
            value: A81F774A-6E87-4C37-BEA0-2F62CC2F374A
          - name: PanacheSoftware__Secret__TaskServiceSecret
            value: 8CDD9C0B-EAD3-4377-A42E-AEEAC9909C0D
          - name: PanacheSoftware__Secret__TeamServiceSecret
            value: 819E2211-EAD4-49D0-84E5-29E6F45587BB
          - name: PanacheSoftware__Secret__CustomFieldServiceSecret
            value: 98E90BBB-2343-4B3B-B008-5A958BE60AF3
          - name: PanacheSoftware__Secret__UIClientSecret
            value: 9C32BBD1-9C08-40FA-96C3-2195F61661F1
          - name: PanacheSoftware__StartDomain
            value: panachesoftware.com
          - name: PanacheSoftware__Url__UIClientURL
            value: http://{server-IP}:30001
          - name: PanacheSoftware__Url__UIClientURLSecure
            value: https://{server-IP}:30001
        image: panachesoftware/panachesoftwareidentity:latest
        name: panachesoftware-identity
        ports:
        - containerPort: 55002
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service
metadata:
  name: panachesoftware-identity-service
spec:
  type: NodePort
  selector:
    app: panachesoftware-identity
  ports:
    - protocol: TCP
      port: 55002
      targetPort: 55002
      nodePort: 30002
