apiVersion: apps/v1
kind: Deployment
metadata:
  name: panachesoftware-service-team
  labels:
    app: panachesoftware-service-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: panachesoftware-service-team
  template:
    metadata:
      labels:
        app: panachesoftware-service-team
    spec:
      containers:
      - env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:55006
          - name: ConnectionStrings__MySQL
            value: server={db-server-IP};port=3306;database=PanacheSoftware.Team.K8S;user={db-user};password={db-password};GuidFormat=Char36
          - name: PanacheSoftware__CallMethod__APICallsSecure
            value: "False"
          - name: PanacheSoftware__CallMethod__UICallsSecure
            value: "False"
          - name: PanacheSoftware__CallMethod__UseAPIGateway
            value: "True"
          - name: PanacheSoftware__DBProvider
            value: MySQL
          - name: PanacheSoftware__Secret__TeamServiceSecret
            value: 819E2211-EAD4-49D0-84E5-29E6F45587BB
          - name: PanacheSoftware__StartDomain
            value: panachesoftware.com
          - name: PanacheSoftware__Url__IdentityServerURL
            value: http://{server-IP}:30002
          - name: PanacheSoftware__Url__IdentityServerURLSecure
            value: https://{server-IP}:30002
        image: panachesoftware/panachesoftwareserviceteam:latest
        name: panachesoftware-service-team
        ports:
        - containerPort: 55006
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service
metadata:
  name: panachesoftware-service-team-service
spec:
  type: NodePort
  selector:
    app: panachesoftware-service-team
  ports:
    - protocol: TCP
      port: 55006
      targetPort: 55006
      nodePort: 30006
