microk8s kubectl apply -f panachesoftware-api-gateway.yaml
microk8s kubectl apply -f panachesoftware-automation-service.yaml
microk8s kubectl apply -f panachesoftware-client-service.yaml
microk8s kubectl apply -f panachesoftware-customfield-service.yaml
microk8s kubectl apply -f panachesoftware-file-service.yaml
microk8s kubectl apply -f panachesoftware-foundation-service.yaml
microk8s kubectl apply -f panachesoftware-identity.yaml
microk8s kubectl apply -f panachesoftware-task-service.yaml
microk8s kubectl apply -f panachesoftware-team-service.yaml
microk8s kubectl apply -f panachesoftware-ui-client.yaml
