DROP TABLE IdentityTenants
DROP TABLE IdentityRoleClaims
DROP TABLE IdentityUserClaims
DROP TABLE IdentityUserLogins
DROP TABLE IdentityUserTokens
DROP TABLE IdentityUserRoles
DROP TABLE IdentityRoles
DROP TABLE IdentityUsers
DROP TABLE ClientAddress
DROP TABLE ClientContact
DROP TABLE ClientDetail
DROP TABLE ClientHeader
DROP TABLE TeamDetail
DROP TABLE UserTeam
DROP TABLE TeamHeader
DROP TABLE LanguageCode
DROP TABLE LanguageItem
DROP TABLE LanguageHeader
DROP TABLE UserSetting
DROP TABLE SettingHeader
DROP TABLE FolderNodeDetail
DROP TABLE FolderNode
DROP TABLE FolderDetail
DROP TABLE TeamFolder
DROP TABLE FolderHeader
DROP TABLE TaskDetail
DROP TABLE TaskHeader
DROP TABLE TaskGroupDetail
DROP TABLE TeamTask
DROP TABLE TaskGroupHeader
DROP TABLE FileVersion
DROP TABLE FileLink
DROP TABLE FileDetail
DROP TABLE FileHeader