version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest

  panachesoftware.identity:
    image: ${DOCKER_REGISTRY-}panachesoftwareidentity
    build:
      context: .
      dockerfile: Web Apps/PanacheSoftware.Identity/Dockerfile
    depends_on:
      - sqldata


  panachesoftware.service.team:
    image: ${DOCKER_REGISTRY-}panachesoftwareserviceteam
    build:
      context: .
      dockerfile: Services/PanacheSoftware.Service.Team/Dockerfile
    depends_on:
      - sqldata
      - panachesoftware.identity


  panachesoftware.service.task:
    image: ${DOCKER_REGISTRY-}panachesoftwareservicetask
    build:
      context: .
      dockerfile: Services/PanacheSoftware.Service.Task/Dockerfile
    depends_on:
      - sqldata
      - panachesoftware.identity
      - panachesoftware.service.team


  panachesoftware.service.foundation:
    image: ${DOCKER_REGISTRY-}panachesoftwareservicefoundation
    build:
      context: .
      dockerfile: Services/PanacheSoftware.Service.Foundation/Dockerfile
    depends_on:
      - sqldata
      - panachesoftware.identity


  panachesoftware.service.file:
    image: ${DOCKER_REGISTRY-}panachesoftwareservicefile
    build:
      context: .
      dockerfile: Services/PanacheSoftware.Service.File/Dockerfile
    depends_on:
      - sqldata
      - panachesoftware.identity


  panachesoftware.service.client:
    image: ${DOCKER_REGISTRY-}panachesoftwareserviceclient
    build:
      context: .
      dockerfile: Services/PanacheSoftware.Service.Client/Dockerfile
    depends_on:
      - sqldata
      - panachesoftware.identity

  panachesoftware.ui.client:
    image: ${DOCKER_REGISTRY-}panachesoftwareuiclient
    build:
      context: .
      dockerfile: Web Apps/PanacheSoftware.UI.Client/Dockerfile
    depends_on:
      - panachesoftware.identity
      - panachesoftware.service.team
      - panachesoftware.service.task
      - panachesoftware.service.foundation
      - panachesoftware.service.file
      - panachesoftware.service.client

