name: Platform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./src/PanacheLegalPlatform.sln
    - name: Build
      run: dotnet build ./src/PanacheLegalPlatform.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/PanacheLegalPlatform.sln --no-restore --verbosity normal
