name: Platform Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/PanacheLegalPlatform.sln
    - name: Build
      run: dotnet build ./src/PanacheLegalPlatform.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/PanacheLegalPlatform.sln --no-restore --verbosity normal
    
    - name: Build and push Docker images PanacheSoftware.UI.Client
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareuiclient
        tags: latest
        dockerfile: ./src/Web Apps/PanacheSoftware.UI.Client/Dockerfile
        path: src/Web Apps/PanacheSoftware.UI.Client
    
    - name: Build and push Docker images PanacheSoftware.Identity
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareidentity
        tags: latest
        dockerfile: ./src/Web Apps/PanacheSoftware.Identity/Dockerfile
        path: src/Web Apps/PanacheSoftware.Identity
    
    - name: Build and push Docker images PanacheSoftware.Service.Client
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareserviceclient
        tags: latest
        dockerfile: ./src/Services/PanacheSoftware.Service.Client/Dockerfile
        path: src/Services/PanacheSoftware.Service.Client
            
    - name: Build and push Docker images PanacheSoftware.Service.File
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareservicefile
        tags: latest
        dockerfile: ./src/Services/PanacheSoftware.Service.File/Dockerfile
        path: src/Services/PanacheSoftware.Service.File
        
    - name: Build and push Docker images PanacheSoftware.Service.Foundation
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareservicefoundation
        tags: latest
        dockerfile: ./src/Services/PanacheSoftware.Service.Foundation/Dockerfile
        path: src/Services/PanacheSoftware.Service.Foundation
        
    - name: Build and push Docker images PanacheSoftware.Service.Task
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareservicetask
        tags: latest
        dockerfile: ./src/Services/PanacheSoftware.Service.Task/Dockerfile
        path: src/Services/PanacheSoftware.Service.Task
        
    - name: Build and push Docker images PanacheSoftware.Service.Team
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: panachesoftware/panachesoftwareserviceteam
        tags: latest
        dockerfile: ./src/Services/PanacheSoftware.Service.Team/Dockerfile
        path: src/Services/PanacheSoftware.Service.Team
