name: Platform Build

on:
  schedule:
  - cron: "0 18 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/PanacheLegalPlatform.sln
    - name: Build
      run: dotnet build ./src/PanacheLegalPlatform.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/PanacheLegalPlatform.sln --no-restore --verbosity normal
